version: "3.9"

services:
  frontend:
    image: node:24-alpine
    container_name: vue-frontend-dev
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
      - node_modules:/app/frontend/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"

# backend:
#   image: node:24-alpine
#   working_dir: /app/backend
#   volumes:
#     - ./backend:/app/backend
#   ports:
#     - "3000:3000"

volumes:
  node_modules: